name: Build and Deploy Package

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      
      - name: Compilar projeto
        run: dotnet build --configuration Release

      - name: Executar testes
        run: dotnet test --configuration Release 

      - name: Empacotar NuGet
        run: dotnet pack --configuration Release

      - name: Publish
        run: dotnet nuget push "MoneyExtension/bin/Release/*.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
